version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pg_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    depends_on:
      - db
    volumes:
      - ./postgrest.conf:/etc/postgrest.conf
    command: postgrest /etc/postgrest.conf
    ports:
      - "3000:3000"

  frontend:
    build: ../frontend
    container_name: rice_frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    # ลบ depends_on: backend ออกเพราะ backend รันข้างนอก Docker